spring:
  application:
    name: InvitationServer


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/andlife?serverTimezone=UTC
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always

r2:
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  endpoint: ${R2_ENDPOINT}
  bucket-name: video-test-boostcamp
  public-url: ${R2_PUBLIC_URL}
  region: auto