name: 서버 배포 자동화

on:
  push:
    branches: [ "dev", "demo" ]
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 권한 부여 및 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
        working-directory: ./backend

      - name: 배포 환경 설정 (브랜치별 분기)
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "demo" ]]; then
            echo "target_dir=/home/ubuntu/andlife-demo" >> $GITHUB_OUTPUT
            echo "server_port=8081" >> $GITHUB_OUTPUT
            echo "db_port=3307" >> $GITHUB_OUTPUT
          else
            echo "target_dir=/home/ubuntu/andlife" >> $GITHUB_OUTPUT
            echo "server_port=8080" >> $GITHUB_OUTPUT
            echo "db_port=3306" >> $GITHUB_OUTPUT
          fi

      - name: 빌드 결과물과 설정 파일들을 EC2로 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "backend/build/libs/*.jar,backend/Dockerfile,backend/docker-compose.yaml"
          target: ${{ steps.set-env.outputs.target_dir }} # 동적 경로
          strip_components: 1

      - name: EC2에서 Docker Compose 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            cd ${{ steps.set-env.outputs.target_dir }}
            export SERVER_PORT=${{ steps.set-env.outputs.server_port }}
            export DB_PORT=${{ steps.set-env.outputs.db_port }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            docker compose down
            docker compose up --build -d